// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuRMdMq1uioefmloO718RXGcM9LnUwJB8',
    appId: '1:855518512229:web:849ce63f99148b187b328c',
    messagingSenderId: '855518512229',
    projectId: 'voice-based-notification',
    authDomain: 'voice-based-notification.firebaseapp.com',
    storageBucket: 'voice-based-notification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Xj_OeVHp4q3FOwXqJSawhrOcRuzZCSs',
    appId: '1:855518512229:android:8fdc9fea0a464c7e7b328c',
    messagingSenderId: '855518512229',
    projectId: 'voice-based-notification',
    storageBucket: 'voice-based-notification.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuRMdMq1uioefmloO718RXGcM9LnUwJB8',
    appId: '1:855518512229:web:3b7b76fdfb865dfb7b328c',
    messagingSenderId: '855518512229',
    projectId: 'voice-based-notification',
    authDomain: 'voice-based-notification.firebaseapp.com',
    storageBucket: 'voice-based-notification.appspot.com',
  );
}
